////dress
[
   
    {
        "producttype_id":4,
        "product_type": "dress",
        "product_name": "Men Solid Bomber jacket",
        "brand": "",
        "color": "white",
        "Size":"5",
        "new_price":558 ,
        "old_price":1029,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"0",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "content": "Min 50% Off",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/kdrpksw0/jacket/z/h/z/xl-aw20-csm-aw-jk0512-campus-sutra-original-imafuhdpq6mtjdqy.jpeg?q=70"
    },
    {
        "producttype_id": 4,
        "product_type": "dress",
        "product_name": "Men cap",
        "brand": "",
        "color": "black",
        "Size":"5",
        "new_price":458,
        "old_price":790,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "content": "Min 50% Off",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kwjkuq80/cap/q/1/r/m-asrcappremium-unisex-woolen-beanie-cap-scarf-warm-snow-proof-original-imag978wdnzmfdwy.jpeg?q=70"
    },
    {
        "producttype_id": 4,
        "product_type": "dress",
        "product_name": "Women's Scarves",
        "content": "Min 50% Off",
        "description": "",
        "brand": "",
        "color": "",
        "Size":"5",
        "new_price":189,
        "old_price":290,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/l4pxk7k0/scarf/c/b/i/free-c2-04-02-fs3-original-imagfkyhjyawg5df.jpeg?q=70"
    },
    {
        "producttype_id": 4,
        "product_type": "dress",
        "product_name": "Women's Shrugs",
        "brand": "NIVIA",
        "color": "white",
        "Size":"5",
        "new_price":558 ,
        "old_price":729,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"Rubber Moulded",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "content": "Min 50% Off",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/xif0q/shrug/r/a/5/xxl-shrug-403-mrn1-iuga-original-imagk3fqkzbztfhf.jpeg?q=70"
    },
    {
        "producttype_id": 4,
        "product_type": "dress",
        "product_name": "Men's track pants",
        "brand": "",
        "color": "white/black",
        "Size":"5",
        "new_price":499 ,
        "old_price":700,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "content": "Min 50% Off",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kzx1a4w0/track-pant/2/6/n/xl-trackpant9013-vitaan-original-imagbtf2jbm9dygg.jpeg?q=70"
    },
    {
        "producttype_id": 4,
        "product_type": "dress",
        "product_name": "Mens's Sweatshirts",
        "brand": "NIVIA",
        "color": "black",
        "Size":"5",
        "new_price":399 ,
        "old_price":1029,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "content": "Min 50% Off",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/xif0q/shopsy-sweatshirt/n/t/3/xl-fc6134-fastcolors-men-original-imagh3s6wqhznywh.jpeg?q=70"
    },
]