//Best of Electronics
[
   
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Projector",
        "brand": "Egate",
        "color": "black",
        "new_price": 5999,
        "old_price": 9999,
        "discount": 4200,
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kge0n0w0/projector/m/q/3/i9-classsic-hd-720p-8908012116066-egate-original-imafwnfzxqp3yymc.jpeg?q=70"
    },

    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Monitor",
        "brand": "Dell",
        "color": "gray",
        "new_price": 8279,
        "old_price": 13999,
        "discount": 65,
        "hidden_stars": 4.2,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kmp7ngw0/monitor/j/z/h/s2721hn-27-py0df-dell-original-imagfjphuywuh2a7.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Top mirrorless cameras",
        "brand": "Canon,sony",
        "color": "black",
        "new_price": 8999,
        "old_price": 12000,
        "discount": 4000,
        "hidden_stars": 4.9,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/l5jxt3k0/dslr-camera/m/n/a/-original-imagg7hsggshhwbz.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Premium PowerBanks",
        "brand": "Mi,realme & more",
        "color": "black",
        "new_price": 3999,
        "old_price": 6999,
        "discount": 65,
        "hidden_stars": 4.2,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/l5jxt3k0/power-bank/b/p/m/power-bank-3-pd-22-5w-10000-rtx2108-realme-original-imagg7jckgt9zgag.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Top Deals of Camera Accessori..",
        "brand": "Tripods,Gimbals ,bags.",
        "color": "white",
        "new_price": 5999,
        "old_price": 9499,
        "discount": 2505,
        "hidden_stars": 4.8,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/ks7tuvk0/gimbal/v/z/7/0-43-om4-se-dji-original-imag5u6rgsdh6k4g.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Best of hair Dryers..",
        "brand": "philips,nova,havells & more.",
        "color": "Purple",
        "new_price": 399,
        "old_price": 600,
        "discount": 150,
        "hidden_stars": 4.2,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/hair-dryer/c/t/g/philips-hp8100-46-original-imaemymzuxrnzfjb.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Printers",
        "brand": "Canon",
        "color": "black",
        "new_price": 2336,
        "old_price": 4999,
        "discount": 2500,
        "hidden_stars": 4.2,
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kb89ea80/printer/g/q/2/canon-ts307-direct-wifi-original-imafsmk9yu57jagn.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "Electronics",
        "product_name": "Monitors",
        "brand": "SAMSUNG",
        "color": "black",
        "new_price": 9999,
        "old_price": 15000,
        "discount": 4500,
        "hidden_stars": 4.2,
        "Display": "55.88 cm (22 inch) LED Backlit Display",
        "Panel Type": "IPS Panel",
        "Resolution": "1920 x 1080 pixels",
        "Screen Resolution Type": "Full HD",
        "Sales Package": "1 Monitor, Power Cable",
        "Screen Form Factor": "Flat",
        "delivery_type": "Free delivery",
        "description": "",
        "product_image": "https://rukminim1.flixcart.com/image/312/312/kynb6vk0/monitor/1/n/s/lf22t354fhwxxl-full-hd-22-lf22t354fhwxxl-samsung-original-imagats2rjbg9uhv.jpeg?q=70"

    },

]