// Winter Essentials  products
[

    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "men's cap",
        "brand": "",
        "color": "black",
        "Size":"Free",
        "new_price": 499,
        "old_price":899 ,
        "discount": 400,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kcp4osw0/cap/5/t/2/free-combo-woolen-cap-muffler-and-gloves-poshing-original-imaftrycnbfus837.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "Men Track Suit",
        "brand": "",
        "color": "white",
        "Size":"S M L XL XXL",
        "new_price": 799,
        "old_price":3999 ,
        "discount": 1500,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/xif0q/track-suit/l/m/n/m-track-suit-for-men-adi-foxter-original-imaghnzeqzy6zmqn.jpeg?q=70"
    },  {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "2 Men Solid, Printed Black, Blue Track Pants",
        "brand": "",
        "color": "",
        "Size":"M X XL",
        "new_price":3999 ,
        "old_price": 379,
        "discount":2300 ,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/kzd147k0/track-pant/f/x/s/xxl-av104c-nstripe-blk-navy-avolt-original-imagbeagkxe88hkw.jpeg?q=70"
    },  {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "Msfashion Printed Chiffon Women Scarf, Stole",
        "brand": "",
        "color": "",
        "Size":"Free",
        "new_price": 1099,
        "old_price": 216,
        "discount": 800,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/l4pxk7k0/scarf/j/u/h/free-size-090-msfashion-original-imagfkazqkw289zw.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "Men & Women Full Sleeve Printed Hooded Sweatshirt",
        "brand": "",
        "color": "white",
        "Size":"Free",
        "new_price":2400 ,
        "old_price": 600,
        "discount": 1800,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/832/832/xif0q/sweatshirt/1/j/t/s-hd-01-tryagain-original-imagkvfhkgfdsykn.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "men's cap",
        "brand": "",
        "color": "black",
        "Size":"Free",
        "new_price": 857,
        "old_price": 285,
        "discount":500 ,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/832/832/kjhgzgw0-0/cap/g/c/b/free-winter-woolen-comboi-cap-scarf-black-and-gloves-set-color-original-imafzfeest9xk6gw.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "kids,Pure Wool Poncho",
        "brand": "",
        "color": "",
        "Size":"0 - 6 ,Months 6 - 12 Months",
        "new_price":999 ,
        "old_price": 499,
        "discount": 400,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/xif0q/poncho/b/e/1/6-12-months-tcc-034-the-comfort-closet-original-imagh5ymaumkp94s.jpeg?q=70"
    },
    {
        "producttype_id": 1,
        "product_type": "EssentialsWinter",
        "product_name": "Turtle Neck Dark Blue Sweater",
        "brand": "",
        "color": "black",
        "Size":"Free",
        "new_price": 4999,
        "old_price":2499 ,
        "discount": 2200,
        "Warranty":"NO",
        "hidden_stars": 4.7,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/xif0q/sweater/g/u/8/l-black-high-neck-b-fashlook-original-imagju9urdmaqaaz.jpeg?q=70"
    },
]