//=============Furniture===============
[
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "Wakefit Leatherette Manual Recliner  (Finish Color - Dark Fantasy, DIY(Do-It-Yourself))",
        "brand": "",
        "color": "dark",
        "Size":"",
        "new_price":17500,
        "old_price":25000,
        "discount": 0,
        "Warranty":"3 years",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Capacity":"1 Seater",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/kw5ag7k0/recliner/g/r/9/96-1-seater-dark-fantasy-96-leatherette-wrclsgrn1lrdf-wakefit-original-imag8w5k9hgxadsq.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "Hometown Leatherette Manual Recliner  (Finish Color - Brown, Knock Down)",
        "brand": "",
        "color": "brown",
        "Size":"",
        "new_price":86900,
        "old_price":149900,
        "discount": 0,
        "Capacity":"3 Seater",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/kua4r680/recliner/h/u/o/93-3-seater-brown-198-leatherette-830025120001-hometown-101-original-imag7fzymshqsjhq.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "Trevi Kyoto Engineered Wood Queen Bed  (Finish Color - Dark Maple, Delivery Condition - Knock Down)",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":9932,
        "old_price":34900,
        "discount": 20000,
        "Capacity":"2",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/l51d30w0/bed/e/p/c/king-brown-no-particle-board-no-kyoto-dark-maple-trevi-dark-original-imagfsstsnk55bzc.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": " Perfect Homes Julian Engineered Wood 4 Door Wardrobe  (Finish Color - Dark Espresso, Mirror Included, Knock Down)",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":15900,
        "old_price":20900,
        "discount": 5000,
        "Capacity":"",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/xif0q/wardrobe-closet/r/x/2/-original-imaggr65wfqnkcs2.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "Office chairs",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":7500,
        "old_price":15000,
        "discount": 0,
        "Capacity":"",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kf75fgw0/office-study-chair/z/g/w/carbon-steel-low-back-royal-ergonomic-desk-mesh-chair-in-brown-original-imafvzvprhk3xqdc.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "office study table",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":8566,
        "old_price":12099,
        "discount":0,
        "Capacity":"",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/k687wy80/office-study-table/y/h/f/particle-board-vi-ct-ph-ost-wb-13-flipkart-perfect-homes-studio-original-imafzkwv94yn5bhg.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "sofa",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":7999,
        "old_price":18999,
        "discount": 0,
        "Capacity":"",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/jim0x3k0/sofa-sectional/c/v/7/blue-polycotton-ph0003-perfect-homes-by-flipkart-blue-original-imaf6dhhsfhvvjdn.jpeg?q=70"
    },
    {
        "producttype_id": 7,
        "product_type": "Furniture",
        "product_name": "mattresses",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":18999,
        "old_price":23000,
        "discount": 0,
        "Capacity":"",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/k7f34i80/bed-mattress/d/x/w/queen-6-72-66-lady-indiana-bonnell-spring-repose-original-imafpnhrnvnjrmfb.jpeg?q=70"
    },
]