//kitchen
[
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Door mates",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":339,
        "old_price":599,
        "discount": 49,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "MAA HOME CONCEPT Microfiber Floor Mat (DK Brown, Large)",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/l4x2rgw0/mat/y/m/e/small-anti-skid-doormats-for-bathroom-entrance-and-bedrooms-original-imagfppfexh9ns3r.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "door curtains",
        "brand": "",
        "color": "blue",
        "Size":"",
        "new_price":999,
        "old_price":1399,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/l5iid8w0/curtain/c/w/j/blue-blossoms-213-door-fs2pc001353dr-eyelet-fashion-string-original-imagg68893hsxpak.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Backpack Sprayer",
        "brand": "",
        "color": "gold",
        "Size":"",
        "new_price":899,
        "old_price":1099,
        "discount": 200,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kqwobrk0/spray-tip/2/t/h/brass-nozzle-water-spray-gun-water-jet-hose-nozzles-hose-pipe-original-imag4tyraqzzwwfg.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Rajali Small Idli Pot ( 2Plates, 9 Idlis ) Induction & Standard Idli Maker  (2 Plates , 9 Idlis )",
        "brand": "",
        "color": "silver",
        "Size":"",
        "new_price":626,
        "old_price":926,
        "discount": 320,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/kuh9yfk0/idli-maker/5/w/v/raj007-14-rajali-original-imag7hjndrznczgp.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Ruby Perl Wooden Ladle  (Pack of 7)",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":149,
        "old_price":399,
        "discount": 250,
        "Material":"Wooden",
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/ksw4ccw0/ladle/k/9/n/a1-decorasia-original-imag6cv8fkd23zgs.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Kreyam's Set of 6 Pattern Discs Kitchen Press",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":294,
        "old_price":394,
        "discount": 100,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/xif0q/kitchen-press/g/z/q/1-1-4-6-kreyam-s-original-imagkyhgffxzszpy.jpeg?q=70"
    },
    {
        "producttype_id": 5,
        "product_type": "Kitchen",
        "product_name": "Non Stick Appam Patra with Lid and Side Handle/ kulipaniyaram pan",
        "brand": "",
        "color": "262",
        "Size":"",
        "new_price":262,
        "old_price":362,
        "discount": 100,
        "Warranty":"NO",
        "Stitching Type":"",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/kpinwy80/pot-pan/v/z/2/appma-787-underzone-original-imag3qg7wbcf3ejx.jpeg?q=70"
    },
]