//===========Sports============
[
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "NIVIA Storm Football - Size: 5  (Pack of 1, Multicolor)",
        "brand": "NIVIA",
        "color": "white",
        "Size":"5",
        "new_price":499 ,
        "old_price":729,
        "discount": 0,
        "Warranty":"NO",
        "Stitching Type":"Rubber Moulded",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/jjolt3k0/ball/j/b/6/400-22-5-country-colour-1-1360br-football-nivia-original-imaf746mud9cxqgh.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "Helmet  (Matt Black)",
        "brand": "",
        "color": "black",
        "Size":"M",
        "new_price":752 ,
        "old_price":1299,
        "discount": 350,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kz5vwy80/helmet/o/4/k/-original-imagb8azfdthjhqr.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "CRADIAC SQUAD SINGLE SPEED 29 T Mountain/Hardtail Cycle  (Single Speed, Blue, Red)",
        "brand": "",
        "color": "green",
        "Size":"Free",
        "new_price":12500 ,
        "old_price":43999,
        "discount": 25500,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "Services":"Cash on Delivery available",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/xif0q/cycle/3/d/o/squad-single-speed-29-18-5-cradiac-120-single-speed-original-imagkyaymu5ajxgm.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "Cricket Bat ",
        "brand": "",
        "color": "black",
        "Size":"Long Handle",
        "new_price":499,
        "old_price":1099,
        "discount": 600,
        "Warranty":"NO",
        "Services":"Cash on Delivery available",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/xif0q/bat/h/8/d/800-full-size-pvc-hard-plastic-cricket-bat-for-age-15-pvc-original-imagj772je2hryrg.jpeg?q=70"
    },

    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "MRF Cricket Bat",
        "brand": "MRF",
        "color": "white",
        "Size":" Short Handle",
        "new_price":599,
        "old_price":1249,
        "discount": 0,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "Services":"Cash on Delivery available",
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/k186fm80/bat/9/f/n/1000-1200-short-handle-endorsed-for-light-hard-tennis-ball-with-original-imafkuuyxrrphkbr.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "PUMA TeamFinal Wave Ball Football - Size: 5",
        "brand": "",
        "color": "white",
        "Size":"5",
        "new_price":1299,
        "old_price":799,
        "discount": 0,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "Services":"Cash on Delivery available",
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/xif0q/ball/h/f/s/-original-imaghkmy3y66sg8f.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "MRF (SIZE-06) BAT + 1BALL COMBO Poplar Willow Cricket Bat",
        "brand": "MRF",
        "color": "white",
        "Size":"",
        "new_price":599 ,
        "old_price":799,
        "discount": 0,
        "Services":"Cash on Delivery available",
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/l5ld8y80/bat/c/m/x/0-5-mrf-junior-size-01-bat-1-ball-bat-combo-1-1005-grade-1-original-imagg8dhh9y4spyp.jpeg?q=70"
    },
    {
        "producttype_id": 3,
        "product_type": "Sports",
        "product_name": "Corner ceat junior size-03 (bat +2ball ) Poplar Willow Cricket Bat  (0.4 kg)",
        "brand": "",
        "color": "",
        "Size":"",
        "new_price":399 ,
        "old_price":999,
        "discount": 0,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "Services":"Cash on Delivery available",
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/l4ssfww0/kit/y/d/0/junior-size-03-bat-2ball-1005-3-creative-corner-25-original-imagfhyhcyfa3sz2.jpeg?q=70"
    },
    
]