////

[
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "The Grow More 360Ã?Â° Revolving Spice Rack Masala Rack Spice Box Masala Box Masala Container",
        "brand": "",
        "color": "gray",
        "Size":"Free",
        "new_price":1649 ,
        "old_price": 299,
        "discount": 0,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kiow6fk0-0/container/4/z/o/360-revolving-spice-rack-masala-rack-spice-box-masala-box-masala-original-imafyfad6jxvbhfs.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "Baby Girls Short/Mid Thigh Casual Dress  (Multicolor, Full Sleeve)",
        "brand": "",
        "color": "pink",
        "Size":"Free",
        "new_price": 999,
        "old_price": 290,
        "discount": 700,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/ktop5e80/kids-dress/t/8/t/18-24-months-muskan-collctn-29-muskan-collection-original-imag6zfe5d8gx7rg.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "LS2914 Day and Date Functioning Blue Avatar Leather Strap Quartz Operated Analog Watch - For Men",
        "brand": "",
        "color": "green",
        "Size":"Free",
        "new_price": 299,
        "old_price":2999 ,
        "discount": 2700,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/ke1pnrk0-0/watch/j/l/0/f-tm519-timor-original-imafutgyfsstzhav.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "CRAFTIFY High Quality 1500 W Immersion Heater Rod  (Water)",
        "brand": "",
        "color": "white",
        "Size":"Free",
        "new_price": 599,
        "old_price":1099 ,
        "discount": 500,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/612/612/ks6ef0w0/immersion-rod/l/a/x/1000-high-quality-craftify-original-imag5t3ygd6dh2q3.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "Nirvika Stainless Steel Handi Set Copper Bottom handi set of 5 Cookware",
        "brand": "",
        "color": "silver",
        "Size":"Free",
        "new_price":900 ,
        "old_price":1990 ,
        "discount": 1000,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/kl2mljk0/bowl/e/x/z/nol-copperhandilid-005-nol-copperhandilid-005-nirvika-original-imagyacc9xbgcaaf.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "Girls Lehenga Choli Ethnic Wear Embroidered Ghagra, Choli, Dupatta Set  (Green, Pack of 1)",
        "brand": "",
        "color": "green",
        "Size":"6-10year",
        "new_price": 299,
        "old_price": 999,
        "discount": 700,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/416/416/kfcv6vk0/kids-lehenga-choli/j/5/e/5-6-years-nano-g-butto-5-6-nivudi-creation-original-imafvub9yjkjxxyy.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "Women White Sling Bag",
        "brand": "",
        "color": "white",
        "Size":"Free",
        "new_price":899 ,
        "old_price": 1799,
        "discount": 999,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/kpwybgw0/hand-messenger-bag/h/r/c/jmm-handbag-jmm-hb-messenger-bag-uptouch-original-imag4fh3x2y2fscb.jpeg?q=70"
    },
    {
        "producttype_id": 2,
        "product_type": "WeddingGifts",
        "product_name": "RBGIIT Copper Bottom Kitchen Serving Cooking Bowl biryani, rice Handi/Pot/Patila Cookware Set  (Stainless Steel, 4 - Piece)",
        "brand": "",
        "color": "silver",
         "Size":"",
        "new_price":999 ,
        "old_price":1599 ,
        "discount": 500,
        "Warranty":"NO",
        "hidden_stars": 2.0,
        "description": "",
        "delivery_type": "Free delivery",
        "product_image": "https://rukminim1.flixcart.com/image/200/200/k77xx8w0/pot-pan/g/w/e/dms0001-dmsexim-original-imafphhbbscdzqk3.jpeg?q=70"
    },

]